### ISSUE TITLE
with py2 torch0.3.1 break with an error

### ISSUE THREAD

**Issue by herbertchen1** [tuzhucheng/sentence-similarity#4]
Traceback (most recent call last):
  File "/baseline/sentence-similarity/main.py", line 67, in <module>
    runner.run(args.epochs, train_loader, dev_loader, test_loader, args.log_interval)
  File "/baseline/sentence-similarity/runners/__init__.py", line 76, in run
    trainer.run(train_loader, max_epochs=epochs)
  File "build/bdist.linux-x86_64/egg/ignite/engine/engine.py", line 223, in run
  File "build/bdist.linux-x86_64/egg/ignite/engine/engine.py", line 188, in _handle_exception
**IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices**
what should i do to fix it？

**Comment by tuzhucheng** [comment]
Hi @herbertchen1 thanks for creating the issue. May I please know the exact command you ran?

Also, this repo is designed with Python 3.6 in mind.

**Comment by herbertchen1** [comment]
Thanks very much, its very helpful!!!
