### ISSUE TITLE
subprocess.CalledProcessError:

### ISSUE THREAD

**Issue by zou-longkun** [tuzhucheng/sentence-similarity#7]
Traceback (most recent call last):
  File "main.py", line 67, in <module>
    runner.run(args.epochs, train_loader, dev_loader, test_loader, args.log_interval)
  File "/home/zoulongkun/project/sentence-similarity-master/runners/__init__.py", line 76, in run
    trainer.run(train_loader, max_epochs=epochs)
  File "/home/zoulongkun/anaconda3/envs/py36/lib/python3.6/site-packages/ignite/engine/engine.py", line 359, in run
    self._handle_exception(e)
  File "/home/zoulongkun/anaconda3/envs/py36/lib/python3.6/site-packages/ignite/engine/engine.py", line 324, in _handle_exception
    raise e
  File "/home/zoulongkun/anaconda3/envs/py36/lib/python3.6/site-packages/ignite/engine/engine.py", line 350, in run
    self._fire_event(Events.EPOCH_COMPLETED)
  File "/home/zoulongkun/anaconda3/envs/py36/lib/python3.6/site-packages/ignite/engine/engine.py", line 259, in _fire_event
    func(self, *(event_args + args), **kwargs)
  File "/home/zoulongkun/project/sentence-similarity-master/runners/__init__.py", line 41, in log_validation_results
    evaluator.run(val_loader)
  File "/home/zoulongkun/anaconda3/envs/py36/lib/python3.6/site-packages/ignite/engine/engine.py", line 359, in run
    self._handle_exception(e)
  File "/home/zoulongkun/anaconda3/envs/py36/lib/python3.6/site-packages/ignite/engine/engine.py", line 324, in _handle_exception
    raise e
  File "/home/zoulongkun/anaconda3/envs/py36/lib/python3.6/site-packages/ignite/engine/engine.py", line 350, in run
    self._fire_event(Events.EPOCH_COMPLETED)
  File "/home/zoulongkun/anaconda3/envs/py36/lib/python3.6/site-packages/ignite/engine/engine.py", line 259, in _fire_event
    func(self, *(event_args + args), **kwargs)
  File "/home/zoulongkun/anaconda3/envs/py36/lib/python3.6/site-packages/ignite/metrics/metric.py", line 68, in completed
    result = self.compute()
  File "/home/zoulongkun/project/sentence-similarity-master/metrics/retrieval_metrics.py", line 71, in compute
    retrieval_metrics = super(MAP, self).compute()
  File "/home/zoulongkun/project/sentence-similarity-master/metrics/retrieval_metrics.py", line 54, in compute
    trec_out = subprocess.check_output([trec_eval_path, '-m', 'map', '-m', 'recip_rank', qrel_fname, results_fname])
  File "/home/zoulongkun/anaconda3/envs/py36/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/home/zoulongkun/anaconda3/envs/py36/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home/zoulongkun/project/sentence-similarity-master/metrics/trec_eval-9.0.5/trec_eval', '-m', 'map', '-m', 'recip_rank', 'aadd85dc-8a12-4f6c-919e-1bed484f3251.qrel', 'aadd85dc-8a12-4f6c-919e-1bed484f3251.results']' died with <Signals.SIGSEGV: 11>.

How can I fix this issue?

**Comment by tuzhucheng** [comment]
Thanks for your interest in the project!

If you cd into the metrics directory, are you able to run `get_trec_eval.sh` successfully?
